# -*- coding: utf-8 -*-
"""
/***************************************************************************
 PD_GUGiK
                                 A QGIS plugin
 Wtyczka do pobierania działek i budynków z usługi zbiorczej WFS EGIB
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-01-17
        copyright            : (C) 2026 by Łukasz Świątek - Główny Urząd Geodezji i Kartografii
        email                : lukasz.swiatek1996@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load PD_GUGiK class from file PD_GUGiK.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .pobierz_dane_GUGiK import PD_GUGiK
    return PD_GUGiK(iface)
